# Generated by Django 4.2 on 2024-08-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('E', 'Eléctrico'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
